name: Convert Clash Rules

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 UTC（北京时间 08:00）触发
  workflow_dispatch:  # 允许手动触发

jobs:
  check-and-convert:
    runs-on: ubuntu-latest
    steps:
      - name: 检查出发原因
        run: echo "启动 Clash 规则转换任务"

      # 1. 获取最新 Release 信息
      - name: 获取最新 Clash Rules Release 版本
        id: get_latest_release
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/Loyalsoldier/clash-rules/releases/latest | jq -r '.tag_name')
          if [ -z "$LATEST_RELEASE" ] || [ "$LATEST_RELEASE" = "null" ]; then
            echo "未找到最新版本，退出..."
            exit 1
          fi
          echo "最新版本: $LATEST_RELEASE"
          echo "LATEST_RELEASE=$LATEST_RELEASE" >> $GITHUB_ENV

      # 2. 下载 Clash Rules Release 下的所有 .txt 规则
      - name: 下载最新的规则文件
        run: |
          mkdir -p rules
          cd rules
          FILES=(applications.txt cncidr.txt direct.txt gfw.txt google.txt greatfire.txt lancidr.txt private.txt reject.txt telegramcidr.txt tld-not-cn.txt)
          for file in "${FILES[@]}"; do
            wget -q --retry-connrefused --waitretry=5 --timeout=30 --tries=5 "https://github.com/Loyalsoldier/clash-rules/releases/download/${{ env.LATEST_RELEASE }}/$file" || { echo "下载 $file 失败"; exit 1; }
          done
          ls -l

      # 3. 安装 mihomo （使用 .deb 版本）
      - name: 获取 mihomo 最新版本号
        id: get_mihomo_version
        run: |
          MIHOMO_VERSION=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest | jq -r '.tag_name')
          if [ -z "$MIHOMO_VERSION" ] || [ "$MIHOMO_VERSION" = "null" ]; then
            echo "未找到 mihomo 最新版本，退出..."
            exit 1
          fi
          echo "MIHOMO_VERSION=$MIHOMO_VERSION" >> $GITHUB_ENV

      - name: 安装 mihomo
        run: |
          wget -q "https://github.com/MetaCubeX/mihomo/releases/download/${{ env.MIHOMO_VERSION }}/mihomo-linux-amd64-${{ env.MIHOMO_VERSION }}.deb" -O mihomo.deb
          sudo dpkg -i mihomo.deb
          rm mihomo.deb

      - name: 确保 mihomo 可用
        run: |
          mihomo -v || { echo "mihomo 安装失败"; exit 1; }

      - name: 转换 .txt 文件为 .mrs
        run: |
          mkdir -p converted_rules
          for file in rules/*.txt; do
            base_name=$(basename "$file" .txt)
            mihomo convert-ruleset domain text "$file" "converted_rules/$base_name.mrs"
          done
          ls -l converted_rules

      - name: 上传转换后的文件到仓库
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add converted_rules/*
          git commit -m "更新 Clash 规则 MRS 格式: ${{ env.LATEST_RELEASE }}" || echo "No changes to commit"
          git push origin main || echo "No changes to push"
          
      # 4. 上传转换后的 .mrs 文件到 Release
      - name: 发布到 GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ env.LATEST_RELEASE }}" converted_rules/Loyalsoldier/* --title "Converted Rules ${{ env.LATEST_RELEASE }}" --notes "自动转换 Clash 规则为 MRS 格式" || echo "Release already exists"
